#!/bin/bash

# Claude Code Pro를 사용하는 로컬 실행 스크립트
# 이미 로그인된 Claude Code 세션을 활용

set -e

echo "🤖 Claude Code Task Runner (using existing session)"
echo "================================================"

# Git 최신 상태 가져오기 (remote가 있을 때만)
if git remote -v | grep -q origin; then
    echo "📥 Pulling latest changes..."
    git pull origin main || true
else
    echo "📥 Working locally (no remote configured)"
fi

# tasks 디렉토리에서 pending 작업 찾기
TASK_DIR="tasks"
if [ ! -d "$TASK_DIR" ]; then
    echo "No tasks directory found. Waiting for tasks..."
    exit 0
fi

# pending 상태의 작업 찾기 (task-*.json 또는 *.json 모두 확인)
for task_file in $TASK_DIR/*.json; do
    [ -e "$task_file" ] || continue
    
    # JSON 파싱 (jq가 없으면 grep 사용)
    if command -v jq &> /dev/null; then
        STATUS=$(jq -r '.status' "$task_file")
        TASK=$(jq -r '.task' "$task_file")
        ID=$(jq -r '.id' "$task_file")
        MACHINE=$(jq -r '.machine' "$task_file")
    else
        STATUS=$(grep -oP '"status":\s*"\K[^"]+' "$task_file" || echo "")
        TASK=$(grep -oP '"task":\s*"\K[^"]+' "$task_file" || echo "")
        ID=$(grep -oP '"id":\s*"\K[^"]+' "$task_file" || echo "")
        MACHINE=$(grep -oP '"machine":\s*"\K[^"]+' "$task_file" || echo "")
    fi
    
    # 현재 머신용 pending 작업만 처리 (hostname 또는 환경변수 MACHINE_NAME 사용)
    CURRENT_MACHINE="${MACHINE_NAME:-$(hostname)}"
    if [ "$STATUS" = "pending" ] && [ "$MACHINE" = "$CURRENT_MACHINE" ]; then
        echo "📋 Found task #$ID: $TASK"
        
        # 작업 상태를 in_progress로 변경
        sed -i '' 's/"status": "pending"/"status": "in_progress"/' "$task_file"
        git add "$task_file"
        git commit -m "task: Start processing task #$ID"
        
        # remote가 있을 때만 push
        if git remote -v | grep -q origin; then
            git push
        fi
        
        # CLAUDE.md 업데이트
        cat > CLAUDE.md << EOF
# Task #$ID

$TASK

## Guidelines
- Follow the development guidelines
- Write clean, maintainable code
- Add tests for new features
- Update documentation as needed
- Create meaningful commits
EOF
        
        # Claude Code 실행 (이미 로그인된 세션 사용)
        echo "🚀 Running Claude Code..."
        
        # 권한 자동 승인 옵션으로 실행
        claude --dangerously-skip-permissions "$TASK" || true
        
        # 변경사항 커밋
        if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "feat: Complete task #$ID - $TASK"
            
            # remote가 있을 때만 PR 생성
            if git remote -v | grep -q origin; then
                # PR 생성을 위한 브랜치 생성
                BRANCH_NAME="task-$ID-$(date +%s)"
                git checkout -b "$BRANCH_NAME"
                git push -u origin "$BRANCH_NAME"
            
                # GitHub CLI로 PR 생성 (설치되어 있다면)
                if command -v gh &> /dev/null; then
                    gh pr create \
                        --title "[Task #$ID] $TASK" \
                        --body "## Automated task completion

**Task ID**: $ID
**Description**: $TASK
**Completed by**: Claude Code on $(hostname)

This PR was automatically generated by the local Claude Code runner.
Changes will be reviewed by Gemini." \
                        --label "automated,claude-code"
                fi
                
                git checkout main
            fi
        fi
        
        # 작업 완료 표시
        sed -i '' 's/"status": "in_progress"/"status": "completed"/' "$task_file"
        git add "$task_file"
        git commit -m "task: Complete task #$ID"
        
        # remote가 있을 때만 push
        if git remote -v | grep -q origin; then
            git push
        fi
        
        echo "✅ Task #$ID completed!"
        
        # Gemini 리뷰 자동 실행
        echo "🔍 Running Gemini review..."
        CHANGED_FILES=$(git diff HEAD~1 --name-only | grep -E '\.(js|ts|py|go|java)$' || true)
        if [ -n "$CHANGED_FILES" ]; then
            export CHANGED_FILES
            export GEMINI_API_KEY="${GEMINI_API_KEY:-AIzaSyA8tKjtfEn-FP4mlTBPRY2GBC3szA-dCFc}"
            node "$SCRIPT_DIR/../src/review.js" || true
            
            # 리뷰 결과가 있으면 자동 개선
            if [ -f "review-results.json" ] && [ -s "review-results.json" ]; then
                echo "📝 Applying review improvements..."
                
                # 리뷰 요약 추출
                REVIEW_SUMMARY=$(cat review-results.json | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    if isinstance(data, list) and len(data) > 0:
        comment = data[0].get('comment', '')
        # JSON 내부의 JSON 파싱
        import re
        matches = re.findall(r'\"comment\": \"([^\"]+)\"', comment)
        for i, match in enumerate(matches[:3]):
            print(f'{i+1}. {match[:100]}')
except: pass
" 2>/dev/null || echo "")
                
                if [ -n "$REVIEW_SUMMARY" ]; then
                    echo "Improvements to apply:"
                    echo "$REVIEW_SUMMARY"
                    
                    # Claude로 개선 실행
                    claude --dangerously-skip-permissions "Apply these code improvements to the files: $REVIEW_SUMMARY" || true
                    
                    # 개선사항 커밋
                    if [ -n "$(git status --porcelain)" ]; then
                        git add -A
                        git commit -m "refactor: Auto-apply Gemini review improvements"
                        
                        # Push 개선사항
                        if git remote -v | grep -q origin; then
                            git push
                        fi
                        
                        echo "✅ Improvements applied and pushed!"
                    fi
                fi
            fi
        fi
        
        break  # 한 번에 하나의 작업만 처리
    fi
done

echo "🔄 Runner cycle complete"