#!/bin/bash

# 완전 자동화 사이클: 작업 실행 → 리뷰 → 개선

set -e

echo "🔄 Starting Full AI Development Cycle"
echo "======================================"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_ROOT"

# 1단계: Claude로 초기 코드 생성
echo ""
echo "📝 Step 1: Generate initial code with Claude"
echo "---------------------------------------------"
export MACHINE_NAME="local-mac"
"$SCRIPT_DIR/claude-runner.sh"

# 작업이 완료되었는지 확인
if [ ! -n "$(git log --oneline -1 | grep 'feat: Complete task')" ]; then
    echo "⚠️  No task was completed"
    exit 1
fi

# 2단계: Gemini 리뷰 실행
echo ""
echo "🔍 Step 2: Get code review from Gemini"
echo "---------------------------------------"

# 변경된 파일 목록 가져오기
CHANGED_FILES=$(git diff HEAD~1 --name-only | grep -E '\.(js|ts|py|go|java)$' || true)

if [ -z "$CHANGED_FILES" ]; then
    echo "No code files to review"
    exit 0
fi

# Gemini 리뷰 실행
export CHANGED_FILES
node src/review.js || true

# 3단계: 리뷰 결과 확인
echo ""
echo "📊 Step 3: Check review results"
echo "--------------------------------"

if [ -f "review-results.json" ] && [ -s "review-results.json" ]; then
    echo "Review suggestions found:"
    cat review-results.json | python3 -m json.tool || cat review-results.json
    
    # 4단계: Claude로 코드 개선
    echo ""
    echo "🚀 Step 4: Apply improvements with Claude"
    echo "------------------------------------------"
    
    # 리뷰 내용을 요약해서 Claude에게 전달
    REVIEW_SUMMARY=$(cat review-results.json | python3 -c "
import json, sys
data = json.load(sys.stdin)
if isinstance(data, list):
    for item in data[:5]:  # 상위 5개만
        if 'comment' in item:
            print(f\"- {item.get('comment', '')}\"[:100])
" 2>/dev/null || echo "Improve code quality")
    
    echo "Applying these improvements:"
    echo "$REVIEW_SUMMARY"
    
    # Claude로 개선 실행
    claude --dangerously-skip-permissions "Apply these code improvements: $REVIEW_SUMMARY" || true
    
    # 5단계: 개선사항 커밋
    echo ""
    echo "💾 Step 5: Commit improvements"
    echo "------------------------------"
    
    if [ -n "$(git status --porcelain)" ]; then
        git add -A
        git commit -m "refactor: Apply automated review improvements

Based on Gemini review:
$REVIEW_SUMMARY

Automated improvement cycle completed."
        
        echo "✅ Improvements committed!"
        
        # PR 업데이트
        if git remote -v | grep -q origin; then
            git push
            echo "📤 Pushed improvements to PR"
        fi
    else
        echo "No changes to commit"
    fi
else
    echo "No review suggestions to apply"
fi

echo ""
echo "🎉 Full cycle completed!"
echo ""
echo "Summary:"
echo "1. ✅ Code generated by Claude"
echo "2. ✅ Code reviewed by Gemini"
echo "3. ✅ Improvements applied by Claude"
echo "4. ✅ Changes committed and pushed"